//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 03:10:32 PM BRST 
//

package br.inf.portalfiscal.nfe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/>
 *           &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
 *         &lt;/choice>
 *         &lt;element name="xNome">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="xFant" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="enderEmit" type="{http://www.portalfiscal.inf.br/nfe}TEnderecoEmit"/>
 *         &lt;element name="IE" type="{http://www.portalfiscal.inf.br/nfe}TIeDest"/>
 *         &lt;element name="IEST" type="{http://www.portalfiscal.inf.br/nfe}TIe" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="IM">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                 &lt;minLength value="1"/>
 *                 &lt;maxLength value="15"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="CNAE">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                 &lt;pattern value="[0-9]{7}"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "cnpj", "cpf", "xNome", "xFant", "enderEmit",
		"ie", "iest", "im", "cnae" })
@XmlRootElement(name = "emit")
public class Emit {

	@XmlElement(name = "CNPJ")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String cnpj;
	@XmlElement(name = "CPF")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String cpf;
	@XmlElement(required = true)
	protected String xNome;
	protected String xFant;
	@XmlElement(required = true)
	protected TEnderecoEmit enderEmit;
	@XmlElement(name = "IE", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String ie;
	@XmlElement(name = "IEST")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String iest;
	@XmlElement(name = "IM")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String im;
	@XmlElement(name = "CNAE")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String cnae;

	/**
	 * Gets the value of the cnpj property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCNPJ() {
		return cnpj;
	}

	/**
	 * Sets the value of the cnpj property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCNPJ(String value) {
		this.cnpj = value;
	}

	/**
	 * Gets the value of the cpf property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCPF() {
		return cpf;
	}

	/**
	 * Sets the value of the cpf property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCPF(String value) {
		this.cpf = value;
	}

	/**
	 * Gets the value of the xNome property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXNome() {
		return xNome;
	}

	/**
	 * Sets the value of the xNome property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXNome(String value) {
		this.xNome = value;
	}

	/**
	 * Gets the value of the xFant property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXFant() {
		return xFant;
	}

	/**
	 * Sets the value of the xFant property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXFant(String value) {
		this.xFant = value;
	}

	/**
	 * Gets the value of the enderEmit property.
	 * 
	 * @return possible object is {@link TEnderecoEmit }
	 * 
	 */
	public TEnderecoEmit getEnderEmit() {
		return enderEmit;
	}

	/**
	 * Sets the value of the enderEmit property.
	 * 
	 * @param value
	 *            allowed object is {@link TEnderecoEmit }
	 * 
	 */
	public void setEnderEmit(TEnderecoEmit value) {
		this.enderEmit = value;
	}

	/**
	 * Gets the value of the ie property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIE() {
		return ie;
	}

	/**
	 * Sets the value of the ie property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIE(String value) {
		this.ie = value;
	}

	/**
	 * Gets the value of the iest property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIEST() {
		return iest;
	}

	/**
	 * Sets the value of the iest property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIEST(String value) {
		this.iest = value;
	}

	/**
	 * Gets the value of the im property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIM() {
		return im;
	}

	/**
	 * Sets the value of the im property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIM(String value) {
		this.im = value;
	}

	/**
	 * Gets the value of the cnae property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCNAE() {
		return cnae;
	}

	/**
	 * Sets the value of the cnae property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCNAE(String value) {
		this.cnae = value;
	}

}
