//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 03:10:32 PM BRST 
//

package br.inf.portalfiscal.nfe;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the br.inf.portalfiscal.nfe package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: br.inf.portalfiscal.nfe
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Emit }
	 * 
	 */
	public Emit createEmit() {
		return new Emit();
	}

	/**
	 * Create an instance of {@link Det.Prod }
	 * 
	 */
	public Det.Prod createDetProd() {
		return new Det.Prod();
	}

	/**
	 * Create an instance of {@link TEnderecoEmit }
	 * 
	 */
	public TEnderecoEmit createTEnderecoEmit() {
		return new TEnderecoEmit();
	}

	/**
	 * Create an instance of {@link Det.Imposto }
	 * 
	 */
	public Det.Imposto createDetImposto() {
		return new Det.Imposto();
	}

	/**
	 * Create an instance of {@link Det.Imposto.ICMS }
	 * 
	 */
	public Det.Imposto.ICMS createDetImpostoICMS() {
		return new Det.Imposto.ICMS();
	}

	/**
	 * Create an instance of {@link Transporta }
	 * 
	 */
	public Transporta createTransporta() {
		return new Transporta();
	}

	/**
	 * Create an instance of {@link Dest }
	 * 
	 */
	public Dest createDest() {
		return new Dest();
	}

	/**
	 * Create an instance of {@link Det }
	 * 
	 */
	public Det createDet() {
		return new Det();
	}

	/**
	 * Create an instance of {@link Det.Imposto.IPI }
	 * 
	 */
	public Det.Imposto.IPI createDetImpostoIPI() {
		return new Det.Imposto.IPI();
	}

	/**
	 * Create an instance of {@link Sistema }
	 * 
	 */
	public Sistema createSistema() {
		return new Sistema();
	}

	/**
	 * Create an instance of {@link TEnderecoDest }
	 * 
	 */
	public TEnderecoDest createTEnderecoDest() {
		return new TEnderecoDest();
	}

}
