//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 03:10:32 PM BRST 
//

package br.inf.portalfiscal.nfe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}emit"/>
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}dest"/>
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}det"/>
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}transporta"/>
 *       &lt;/choice>
 *       &lt;attribute name="versao" use="required" type="{http://www.portalfiscal.inf.br/nfe}TVerSis" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "emit", "dest", "det", "transporta" })
@XmlRootElement(name = "sistema")
public class Sistema {

	protected Emit emit;
	protected Dest dest;
	protected Det det;
	protected Transporta transporta;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String versao;

	/**
	 * Gets the value of the emit property.
	 * 
	 * @return possible object is {@link Emit }
	 * 
	 */
	public Emit getEmit() {
		return emit;
	}

	/**
	 * Sets the value of the emit property.
	 * 
	 * @param value
	 *            allowed object is {@link Emit }
	 * 
	 */
	public void setEmit(Emit value) {
		this.emit = value;
	}

	/**
	 * Gets the value of the dest property.
	 * 
	 * @return possible object is {@link Dest }
	 * 
	 */
	public Dest getDest() {
		return dest;
	}

	/**
	 * Sets the value of the dest property.
	 * 
	 * @param value
	 *            allowed object is {@link Dest }
	 * 
	 */
	public void setDest(Dest value) {
		this.dest = value;
	}

	/**
	 * Gets the value of the det property.
	 * 
	 * @return possible object is {@link Det }
	 * 
	 */
	public Det getDet() {
		return det;
	}

	/**
	 * Sets the value of the det property.
	 * 
	 * @param value
	 *            allowed object is {@link Det }
	 * 
	 */
	public void setDet(Det value) {
		this.det = value;
	}

	/**
	 * Gets the value of the transporta property.
	 * 
	 * @return possible object is {@link Transporta }
	 * 
	 */
	public Transporta getTransporta() {
		return transporta;
	}

	/**
	 * Sets the value of the transporta property.
	 * 
	 * @param value
	 *            allowed object is {@link Transporta }
	 * 
	 */
	public void setTransporta(Transporta value) {
		this.transporta = value;
	}

	/**
	 * Gets the value of the versao property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersao() {
		return versao;
	}

	/**
	 * Sets the value of the versao property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersao(String value) {
		this.versao = value;
	}

}
