//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 03:10:32 PM BRST 
//

package br.inf.portalfiscal.nfe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpjOpc"/>
 *           &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
 *         &lt;/choice>
 *         &lt;element name="xNome">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="enderDest" type="{http://www.portalfiscal.inf.br/nfe}TEnderecoDest" minOccurs="0"/>
 *         &lt;element name="IE" type="{http://www.portalfiscal.inf.br/nfe}TIeDest" minOccurs="0"/>
 *         &lt;element name="ISUF" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "cnpj", "cpf", "xNome", "enderDest", "ie",
		"isuf" })
@XmlRootElement(name = "dest")
public class Dest {

	@XmlElement(name = "CNPJ")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String cnpj;
	@XmlElement(name = "CPF")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String cpf;
	@XmlElement(required = true)
	protected String xNome;
	protected TEnderecoDest enderDest;
	@XmlElement(name = "IE")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String ie;
	@XmlElement(name = "ISUF")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String isuf;

	/**
	 * Gets the value of the cnpj property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCNPJ() {
		return cnpj;
	}

	/**
	 * Sets the value of the cnpj property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCNPJ(String value) {
		this.cnpj = value;
	}

	/**
	 * Gets the value of the cpf property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCPF() {
		return cpf;
	}

	/**
	 * Sets the value of the cpf property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCPF(String value) {
		this.cpf = value;
	}

	/**
	 * Gets the value of the xNome property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXNome() {
		return xNome;
	}

	/**
	 * Sets the value of the xNome property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXNome(String value) {
		this.xNome = value;
	}

	/**
	 * Gets the value of the enderDest property.
	 * 
	 * @return possible object is {@link TEnderecoDest }
	 * 
	 */
	public TEnderecoDest getEnderDest() {
		return enderDest;
	}

	/**
	 * Sets the value of the enderDest property.
	 * 
	 * @param value
	 *            allowed object is {@link TEnderecoDest }
	 * 
	 */
	public void setEnderDest(TEnderecoDest value) {
		this.enderDest = value;
	}

	/**
	 * Gets the value of the ie property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIE() {
		return ie;
	}

	/**
	 * Sets the value of the ie property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIE(String value) {
		this.ie = value;
	}

	/**
	 * Gets the value of the isuf property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getISUF() {
		return isuf;
	}

	/**
	 * Sets the value of the isuf property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setISUF(String value) {
		this.isuf = value;
	}

}
