//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 03:10:32 PM BRST 
//

package br.inf.portalfiscal.nfe;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cProd">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;maxLength value="60"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="cEAN" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;pattern value="[0-9]{0}|[0-9]{8}|[0-9]{12,14}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="xProd">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;maxLength value="120"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="NCM" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;pattern value="[0-9]{8}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EXTIPI" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;pattern value="[0-9]{2,3}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="genero" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;pattern value="[0-9]{1,2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="uCom" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;maxLength value="6"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="cEANTrib" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;pattern value="[0-9]{0}|[0-9]{8}|[0-9]{12,14}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="uTrib" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;maxLength value="6"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="qTrib" type="{http://www.portalfiscal.inf.br/nfe}TDec_0804"/>
 *                   &lt;element name="vUnCom" type="{http://www.portalfiscal.inf.br/nfe}TDec_1204"/>
 *                   &lt;element name="vUnTrib" type="{http://www.portalfiscal.inf.br/nfe}TDec_1204"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="imposto" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ICMS" maxOccurs="11" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="orig" type="{http://www.portalfiscal.inf.br/nfe}Torig" minOccurs="0"/>
 *                             &lt;element name="CST">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;enumeration value="00"/>
 *                                   &lt;enumeration value="10"/>
 *                                   &lt;enumeration value="20"/>
 *                                   &lt;enumeration value="30"/>
 *                                   &lt;enumeration value="40"/>
 *                                   &lt;enumeration value="41"/>
 *                                   &lt;enumeration value="50"/>
 *                                   &lt;enumeration value="51"/>
 *                                   &lt;enumeration value="60"/>
 *                                   &lt;enumeration value="70"/>
 *                                   &lt;enumeration value="90"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="modBC" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;enumeration value="0"/>
 *                                   &lt;enumeration value="1"/>
 *                                   &lt;enumeration value="2"/>
 *                                   &lt;enumeration value="3"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="pRedBC" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302Opc" minOccurs="0"/>
 *                             &lt;element name="pICMS" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302" minOccurs="0"/>
 *                             &lt;element name="pICMSST" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302" minOccurs="0"/>
 *                             &lt;element name="modBCST" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;enumeration value="0"/>
 *                                   &lt;enumeration value="1"/>
 *                                   &lt;enumeration value="2"/>
 *                                   &lt;enumeration value="3"/>
 *                                   &lt;enumeration value="4"/>
 *                                   &lt;enumeration value="5"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="pMVAST" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302Opc" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="IPI" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="clEnq" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="5"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CNPJProd" type="{http://www.portalfiscal.inf.br/nfe}TCnpj" minOccurs="0"/>
 *                             &lt;element name="cEnq" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="3"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "prod", "imposto" })
@XmlRootElement(name = "det")
public class Det {

	@XmlElement(required = true)
	protected Det.Prod prod;
	protected Det.Imposto imposto;

	/**
	 * Gets the value of the prod property.
	 * 
	 * @return possible object is {@link Det.Prod }
	 * 
	 */
	public Det.Prod getProd() {
		return prod;
	}

	/**
	 * Sets the value of the prod property.
	 * 
	 * @param value
	 *            allowed object is {@link Det.Prod }
	 * 
	 */
	public void setProd(Det.Prod value) {
		this.prod = value;
	}

	/**
	 * Gets the value of the imposto property.
	 * 
	 * @return possible object is {@link Det.Imposto }
	 * 
	 */
	public Det.Imposto getImposto() {
		return imposto;
	}

	/**
	 * Sets the value of the imposto property.
	 * 
	 * @param value
	 *            allowed object is {@link Det.Imposto }
	 * 
	 */
	public void setImposto(Det.Imposto value) {
		this.imposto = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ICMS" maxOccurs="11" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="orig" type="{http://www.portalfiscal.inf.br/nfe}Torig" minOccurs="0"/>
	 *                   &lt;element name="CST">
	 *                     &lt;simpleType>
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *                         &lt;enumeration value="00"/>
	 *                         &lt;enumeration value="10"/>
	 *                         &lt;enumeration value="20"/>
	 *                         &lt;enumeration value="30"/>
	 *                         &lt;enumeration value="40"/>
	 *                         &lt;enumeration value="41"/>
	 *                         &lt;enumeration value="50"/>
	 *                         &lt;enumeration value="51"/>
	 *                         &lt;enumeration value="60"/>
	 *                         &lt;enumeration value="70"/>
	 *                         &lt;enumeration value="90"/>
	 *                       &lt;/restriction>
	 *                     &lt;/simpleType>
	 *                   &lt;/element>
	 *                   &lt;element name="modBC" minOccurs="0">
	 *                     &lt;simpleType>
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *                         &lt;enumeration value="0"/>
	 *                         &lt;enumeration value="1"/>
	 *                         &lt;enumeration value="2"/>
	 *                         &lt;enumeration value="3"/>
	 *                       &lt;/restriction>
	 *                     &lt;/simpleType>
	 *                   &lt;/element>
	 *                   &lt;element name="pRedBC" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302Opc" minOccurs="0"/>
	 *                   &lt;element name="pICMS" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302" minOccurs="0"/>
	 *                   &lt;element name="pICMSST" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302" minOccurs="0"/>
	 *                   &lt;element name="modBCST" minOccurs="0">
	 *                     &lt;simpleType>
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *                         &lt;enumeration value="0"/>
	 *                         &lt;enumeration value="1"/>
	 *                         &lt;enumeration value="2"/>
	 *                         &lt;enumeration value="3"/>
	 *                         &lt;enumeration value="4"/>
	 *                         &lt;enumeration value="5"/>
	 *                       &lt;/restriction>
	 *                     &lt;/simpleType>
	 *                   &lt;/element>
	 *                   &lt;element name="pMVAST" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302Opc" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="IPI" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="clEnq" minOccurs="0">
	 *                     &lt;simpleType>
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *                         &lt;minLength value="1"/>
	 *                         &lt;maxLength value="5"/>
	 *                       &lt;/restriction>
	 *                     &lt;/simpleType>
	 *                   &lt;/element>
	 *                   &lt;element name="CNPJProd" type="{http://www.portalfiscal.inf.br/nfe}TCnpj" minOccurs="0"/>
	 *                   &lt;element name="cEnq" minOccurs="0">
	 *                     &lt;simpleType>
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *                         &lt;minLength value="1"/>
	 *                         &lt;maxLength value="3"/>
	 *                       &lt;/restriction>
	 *                     &lt;/simpleType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "icms", "ipi" })
	public static class Imposto {

		@XmlElement(name = "ICMS")
		protected List<Det.Imposto.ICMS> icms;
		@XmlElement(name = "IPI")
		protected Det.Imposto.IPI ipi;

		/**
		 * Gets the value of the icms property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the icms property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getICMS().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Det.Imposto.ICMS }
		 * 
		 * 
		 */
		public List<Det.Imposto.ICMS> getICMS() {
			if (icms == null) {
				icms = new ArrayList<Det.Imposto.ICMS>();
			}
			return this.icms;
		}

		/**
		 * Gets the value of the ipi property.
		 * 
		 * @return possible object is {@link Det.Imposto.IPI }
		 * 
		 */
		public Det.Imposto.IPI getIPI() {
			return ipi;
		}

		/**
		 * Sets the value of the ipi property.
		 * 
		 * @param value
		 *            allowed object is {@link Det.Imposto.IPI }
		 * 
		 */
		public void setIPI(Det.Imposto.IPI value) {
			this.ipi = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="orig" type="{http://www.portalfiscal.inf.br/nfe}Torig" minOccurs="0"/>
		 *         &lt;element name="CST">
		 *           &lt;simpleType>
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
		 *               &lt;enumeration value="00"/>
		 *               &lt;enumeration value="10"/>
		 *               &lt;enumeration value="20"/>
		 *               &lt;enumeration value="30"/>
		 *               &lt;enumeration value="40"/>
		 *               &lt;enumeration value="41"/>
		 *               &lt;enumeration value="50"/>
		 *               &lt;enumeration value="51"/>
		 *               &lt;enumeration value="60"/>
		 *               &lt;enumeration value="70"/>
		 *               &lt;enumeration value="90"/>
		 *             &lt;/restriction>
		 *           &lt;/simpleType>
		 *         &lt;/element>
		 *         &lt;element name="modBC" minOccurs="0">
		 *           &lt;simpleType>
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
		 *               &lt;enumeration value="0"/>
		 *               &lt;enumeration value="1"/>
		 *               &lt;enumeration value="2"/>
		 *               &lt;enumeration value="3"/>
		 *             &lt;/restriction>
		 *           &lt;/simpleType>
		 *         &lt;/element>
		 *         &lt;element name="pRedBC" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302Opc" minOccurs="0"/>
		 *         &lt;element name="pICMS" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302" minOccurs="0"/>
		 *         &lt;element name="pICMSST" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302" minOccurs="0"/>
		 *         &lt;element name="modBCST" minOccurs="0">
		 *           &lt;simpleType>
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
		 *               &lt;enumeration value="0"/>
		 *               &lt;enumeration value="1"/>
		 *               &lt;enumeration value="2"/>
		 *               &lt;enumeration value="3"/>
		 *               &lt;enumeration value="4"/>
		 *               &lt;enumeration value="5"/>
		 *             &lt;/restriction>
		 *           &lt;/simpleType>
		 *         &lt;/element>
		 *         &lt;element name="pMVAST" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302Opc" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "orig", "cst", "modBC", "pRedBC",
				"picms", "picmsst", "modBCST", "pmvast" })
		public static class ICMS {

			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String orig;
			@XmlElement(name = "CST", required = true)
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String cst;
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String modBC;
			protected String pRedBC;
			@XmlElement(name = "pICMS")
			protected String picms;
			@XmlElement(name = "pICMSST")
			protected String picmsst;
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String modBCST;
			@XmlElement(name = "pMVAST")
			protected String pmvast;

			/**
			 * Gets the value of the orig property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOrig() {
				return orig;
			}

			/**
			 * Sets the value of the orig property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setOrig(String value) {
				this.orig = value;
			}

			/**
			 * Gets the value of the cst property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCST() {
				return cst;
			}

			/**
			 * Sets the value of the cst property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCST(String value) {
				this.cst = value;
			}

			/**
			 * Gets the value of the modBC property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getModBC() {
				return modBC;
			}

			/**
			 * Sets the value of the modBC property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setModBC(String value) {
				this.modBC = value;
			}

			/**
			 * Gets the value of the pRedBC property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPRedBC() {
				return pRedBC;
			}

			/**
			 * Sets the value of the pRedBC property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPRedBC(String value) {
				this.pRedBC = value;
			}

			/**
			 * Gets the value of the picms property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPICMS() {
				return picms;
			}

			/**
			 * Sets the value of the picms property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPICMS(String value) {
				this.picms = value;
			}

			/**
			 * Gets the value of the picmsst property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPICMSST() {
				return picmsst;
			}

			/**
			 * Sets the value of the picmsst property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPICMSST(String value) {
				this.picmsst = value;
			}

			/**
			 * Gets the value of the modBCST property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getModBCST() {
				return modBCST;
			}

			/**
			 * Sets the value of the modBCST property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setModBCST(String value) {
				this.modBCST = value;
			}

			/**
			 * Gets the value of the pmvast property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPMVAST() {
				return pmvast;
			}

			/**
			 * Sets the value of the pmvast property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPMVAST(String value) {
				this.pmvast = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="clEnq" minOccurs="0">
		 *           &lt;simpleType>
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
		 *               &lt;minLength value="1"/>
		 *               &lt;maxLength value="5"/>
		 *             &lt;/restriction>
		 *           &lt;/simpleType>
		 *         &lt;/element>
		 *         &lt;element name="CNPJProd" type="{http://www.portalfiscal.inf.br/nfe}TCnpj" minOccurs="0"/>
		 *         &lt;element name="cEnq" minOccurs="0">
		 *           &lt;simpleType>
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
		 *               &lt;minLength value="1"/>
		 *               &lt;maxLength value="3"/>
		 *             &lt;/restriction>
		 *           &lt;/simpleType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "clEnq", "cnpjProd", "cEnq" })
		public static class IPI {

			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String clEnq;
			@XmlElement(name = "CNPJProd")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String cnpjProd;
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String cEnq;

			/**
			 * Gets the value of the clEnq property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getClEnq() {
				return clEnq;
			}

			/**
			 * Sets the value of the clEnq property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setClEnq(String value) {
				this.clEnq = value;
			}

			/**
			 * Gets the value of the cnpjProd property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCNPJProd() {
				return cnpjProd;
			}

			/**
			 * Sets the value of the cnpjProd property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCNPJProd(String value) {
				this.cnpjProd = value;
			}

			/**
			 * Gets the value of the cEnq property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCEnq() {
				return cEnq;
			}

			/**
			 * Sets the value of the cEnq property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCEnq(String value) {
				this.cEnq = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="cProd">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;maxLength value="60"/>
	 *               &lt;minLength value="1"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="cEAN" minOccurs="0">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;pattern value="[0-9]{0}|[0-9]{8}|[0-9]{12,14}"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="xProd">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;maxLength value="120"/>
	 *               &lt;minLength value="1"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="NCM" minOccurs="0">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;pattern value="[0-9]{8}"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="EXTIPI" minOccurs="0">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;pattern value="[0-9]{2,3}"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="genero" minOccurs="0">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;pattern value="[0-9]{1,2}"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="uCom" minOccurs="0">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;maxLength value="6"/>
	 *               &lt;minLength value="1"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="cEANTrib" minOccurs="0">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;pattern value="[0-9]{0}|[0-9]{8}|[0-9]{12,14}"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="uTrib" minOccurs="0">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
	 *               &lt;maxLength value="6"/>
	 *               &lt;minLength value="1"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="qTrib" type="{http://www.portalfiscal.inf.br/nfe}TDec_0804"/>
	 *         &lt;element name="vUnCom" type="{http://www.portalfiscal.inf.br/nfe}TDec_1204"/>
	 *         &lt;element name="vUnTrib" type="{http://www.portalfiscal.inf.br/nfe}TDec_1204"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "cProd", "cean", "xProd", "ncm",
			"extipi", "genero", "uCom", "ceanTrib", "uTrib", "qTrib", "vUnCom",
			"vUnTrib" })
	public static class Prod {

		@XmlElement(required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String cProd;
		@XmlElement(name = "cEAN")
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String cean;
		@XmlElement(required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String xProd;
		@XmlElement(name = "NCM")
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String ncm;
		@XmlElement(name = "EXTIPI")
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String extipi;
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String genero;
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String uCom;
		@XmlElement(name = "cEANTrib")
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String ceanTrib;
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String uTrib;
		@XmlElement(required = true)
		protected String qTrib;
		@XmlElement(required = true)
		protected String vUnCom;
		@XmlElement(required = true)
		protected String vUnTrib;

		/**
		 * Gets the value of the cProd property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCProd() {
			return cProd;
		}

		/**
		 * Sets the value of the cProd property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCProd(String value) {
			this.cProd = value;
		}

		/**
		 * Gets the value of the cean property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCEAN() {
			return cean;
		}

		/**
		 * Sets the value of the cean property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCEAN(String value) {
			this.cean = value;
		}

		/**
		 * Gets the value of the xProd property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getXProd() {
			return xProd;
		}

		/**
		 * Sets the value of the xProd property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setXProd(String value) {
			this.xProd = value;
		}

		/**
		 * Gets the value of the ncm property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNCM() {
			return ncm;
		}

		/**
		 * Sets the value of the ncm property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNCM(String value) {
			this.ncm = value;
		}

		/**
		 * Gets the value of the extipi property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getEXTIPI() {
			return extipi;
		}

		/**
		 * Sets the value of the extipi property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setEXTIPI(String value) {
			this.extipi = value;
		}

		/**
		 * Gets the value of the genero property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getGenero() {
			return genero;
		}

		/**
		 * Sets the value of the genero property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setGenero(String value) {
			this.genero = value;
		}

		/**
		 * Gets the value of the uCom property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getUCom() {
			return uCom;
		}

		/**
		 * Sets the value of the uCom property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setUCom(String value) {
			this.uCom = value;
		}

		/**
		 * Gets the value of the ceanTrib property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCEANTrib() {
			return ceanTrib;
		}

		/**
		 * Sets the value of the ceanTrib property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCEANTrib(String value) {
			this.ceanTrib = value;
		}

		/**
		 * Gets the value of the uTrib property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getUTrib() {
			return uTrib;
		}

		/**
		 * Sets the value of the uTrib property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setUTrib(String value) {
			this.uTrib = value;
		}

		/**
		 * Gets the value of the qTrib property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getQTrib() {
			return qTrib;
		}

		/**
		 * Sets the value of the qTrib property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setQTrib(String value) {
			this.qTrib = value;
		}

		/**
		 * Gets the value of the vUnCom property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getVUnCom() {
			return vUnCom;
		}

		/**
		 * Sets the value of the vUnCom property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setVUnCom(String value) {
			this.vUnCom = value;
		}

		/**
		 * Gets the value of the vUnTrib property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getVUnTrib() {
			return vUnTrib;
		}

		/**
		 * Sets the value of the vUnTrib property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setVUnTrib(String value) {
			this.vUnTrib = value;
		}

	}

}
